services:
  traefik:
    profiles:
      - disabled

  cvat_server:
    ports:
      - "127.0.0.1:8080:8080"

  cvat_ui:
    ports:
      - "127.0.0.1:8000:80"

  cvat_grafana:
    ports:
      - "127.0.0.1:3000:3000"
